code --install-extension 9j.amvim
code --install-extension antfu.iconify
code --install-extension antfu.icons-carbon
code --install-extension antfu.unocss
code --install-extension artdiniz.quitcontrol-vscode
code --install-extension bierner.markdown-mermaid
code --install-extension bpruitt-goddard.mermaid-markdown-syntax-highlighting
code --install-extension bradlc.vscode-tailwindcss
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension dbaeumer.vscode-eslint
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension fileicons.file-icons
code --install-extension fivethree.vscode-svelte-snippets
code --install-extension foxundermoon.shell-format
code --install-extension GraphQL.vscode-graphql
code --install-extension johnsoncodehk.volar
code --install-extension JuanBlanco.solidity
code --install-extension laggardkernel.vscode-theme-onelight
code --install-extension mhutchie.git-graph
code --install-extension Prisma.prisma
code --install-extension psudo-dev.nebula-oni-theme
code --install-extension silvenon.mdx
code --install-extension stkb.rewrap
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension svelte.svelte-vscode
code --install-extension tamasfe.even-better-toml
code --install-extension theurgi.theme-purple-one
code --install-extension wayou.vscode-todo-highlight
code --install-extension yzhang.markdown-all-in-one
